---
version: '2'
services:
  zookeeper-1:
    image: docker.io/confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888

  zookeeper-2:
    image: docker.io/confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888

  zookeeper-3:
    image: docker.io/confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888

  kafka-1:
    image: docker.io/confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_LISTENERS: INTERNO://:19082,EXTERNO://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNO://:19082,EXTERNO://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNO:PLAINTEXT,EXTERNO:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNO
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.134
  kafka-2:
    image: docker.io/confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_LISTENERS: INTERNO://:29082,EXTERNO://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNO://:29082,EXTERNO://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNO:PLAINTEXT,EXTERNO:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNO
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.134
  kafka-3:
    image: docker.io/confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_LISTENERS: INTERNO://:39082,EXTERNO://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNO://:39082,EXTERNO://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNO:PLAINTEXT,EXTERNO:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNO
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.134
